In [32]:
'''
Libraries: Python libraries is a collection of functions and methods that allows you to perform many actions without writing your code.
    - NumPy
        - Numerical computing
            - to perform complex methametical operations
    - MatplotLib
        - Visualization
            - bar plot, graph chat and scatter plot
    - Pandas
        - Data manupulation
            - just like if we have 100's of data and need to identify resources that are starting from j or n

'''

"\nLibraries: Python libraries is a collection of functions and methods that allows you to perform many actions without writing your code.\n    - NumPy\n        - Numerical computing\n            - to perform complex methametical operations\n    - MatplotLib\n        - Visualization\n            - bar plot, graph chat and scatter plot\n    - Pandas\n        - Data manupulation\n            - just like if we have 100's of data and need to identify resources that are starting from j or n\n\n"

In [33]:
'''
NumPy: 
    - NumPy stands for Numerical python and is the core library for numeric and scientific computing
    - It consists of multi-dimensional arrays objects and a collection of routines for processing those arrays
'''

'\nNumPy: \n    - NumPy stands for Numerical python and is the core library for numeric and scientific computing\n    - It consists of multi-dimensional arrays objects and a collection of routines for processing those arrays\n'

In [34]:
#pip version
!pip --version

pip 21.1.1 from c:\python39\lib\site-packages\pip (python 3.9)



In [35]:
#library install
!pip install numpy

You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.


In [36]:
# single dimensional array
import numpy as np

n1 = np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [37]:
type(n1)

numpy.ndarray

In [38]:
#multi-dimensional

n2 = np.array([[10,20,30,40,50], [60,70,80,90,100]])
n2

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [39]:
type(n2)

numpy.ndarray

In [40]:
'''
Initialize Numpy Array
    - initializing Numpy array with zeros
'''

'\nInitialize Numpy Array\n    - initializing Numpy array with zeros\n'

In [41]:
import numpy as np

#we are making a numpy array with 1 row and 2 columns

n1 = np.zeros((1,2))
n1

array([[0., 0.]])

In [42]:
#we are making a numpy array with 5 row and 5 columns

n2 = np.zeros((5,5))
n2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
'''
Initialize Numpy Array
    - initializing Numpy array with same number
'''

'\nInitialize Numpy Array\n    - initializing Numpy array with same number\n'

In [44]:
n1 = np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

In [45]:
'''
Initialize Numpy Array
    - initializing Numpy array within a range
'''

'\nInitialize Numpy Array\n    - initializing Numpy array within a range\n'

In [46]:
n1 = np.arange(10,20)
#final value is excusive i.e., 20
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [47]:
n1 = np.arange(10,50,5)
#final value is excusive i.e., 50 with a skip of 5
n1

array([10, 15, 20, 25, 30, 35, 40, 45])

In [48]:
'''
Initialize Numpy Array
    - initializing Numpy array with random range
'''

'\nInitialize Numpy Array\n    - initializing Numpy array with random range\n'

In [49]:
#within the range from 1 to 100, please give me 5 random integer values
n1 = np.random.randint(1,100,5)
n1

array([40, 44, 59, 69, 32])

In [50]:
'''
NumPy-Shape:
    - checking the shape of numpy arrays
'''

'\nNumPy-Shape:\n    - checking the shape of numpy arrays\n'

In [57]:
#to check the shape of an array and we can change it as well
n3 = np.array([[1,2,3],[4,5,6]])
n3.shape

(2, 3)

In [58]:
n3

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
# to change the shape
n3.shape = (3,2)
n3.shape

(3, 2)

In [60]:
n3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
'''
Joining NumPy arrays:
    - Vertical stack
        -vstack()
    - Hostizontal stack
        - hstack()
    - column_stack()
'''

'\nJoining NumPy arrays:\n    - Vertical stack\n        -vstack()\n    - Hostizontal stack\n        - hstack()\n    - column_stack()\n'

In [66]:
'''
Vertical stack
    -vstack()
'''

n4 = np.array([10,20,30])
n5 = np.array([40,50,60])

np.vstack((n4,n5))

array([[10, 20, 30],
       [40, 50, 60]])

In [67]:
'''
Hostizontal stack
    - hstack()
'''

n6 = np.array([10,20,30])
n7 = np.array([40,50,60])

np.hstack((n6,n7))

array([10, 20, 30, 40, 50, 60])

In [68]:
'''
column_stack()
'''

n8 = np.array([10,20,30])
n9 = np.array([40,50,60])

np.column_stack((n8,n9))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [71]:
'''
Numpy Intersection(Display Common Elements) 
'''
n10 = np.array([10,20,30,40,50])
n11 = np.array([40,50,60,70,80])

np.intersect1d(n10,n11)

array([40, 50])

In [72]:
'''
Numpy Difference(Remove common elemnts by subtracting)
    - (a-b)
    - (b-a)
n10 = np.array([10,20,30,40,50])
n11 = np.array([40,50,60,70,80])
'''
np.setdiff1d(n10,n11)

array([10, 20, 30])

In [73]:
np.setdiff1d(n11,n10)

array([60, 70, 80])

In [74]:
'''
NumPy Array Mathematics
    - addition of arrays

n10 = np.array([10,20,30,40,50])
n11 = np.array([40,50,60,70,80])
'''

'\nNumPy Array Mathematics\n    - addition of arrays\n'

In [75]:
np.sum([n10,n11])

450

In [76]:
#axis=0 is respect to columns
np.sum([n10,n11], axis=0)

array([ 50,  70,  90, 110, 130])

In [77]:
#axis=1 is respect to rows
np.sum([n10,n11], axis=1)

array([150, 300])

In [78]:
'''
NumPy Array Mathematics
    - Addition
    - Multiplication
    - Division
    - Subtraction

n10 = np.array([10,20,30,40,50])
n11 = np.array([40,50,60,70,80])
'''

'\nNumPy Array Mathematics\n    - Addition\n    - Multiplication\n    - Division\n    - Subtraction\n\nn10 = np.array([10,20,30,40,50])\nn11 = np.array([40,50,60,70,80])\n'

In [79]:
#Addition
n12 = n10+1
n12

array([11, 21, 31, 41, 51])

In [80]:
#multiplication
n13 = n10 * 2
n13

array([ 20,  40,  60,  80, 100])

In [81]:
#Subtraction
n14 = n12 - 1
n14

array([10, 20, 30, 40, 50])

In [83]:
#division
n15 = n10/2
n15

array([ 5., 10., 15., 20., 25.])

In [84]:
'''
NumPy Math Functions
    - Mean
    - Standard deviation
    - Median
'''

'\nNumPy Math Functions\n    - Mean\n    - Standard deviation\n    - Median\n'

In [85]:
#Mean
n16 = np.array([10,20,30,40,50,60])
np.mean(n16)

35.0

In [86]:
#Standard Deviation
np.std(n16)

17.07825127659933

In [87]:
#median
np.median(n16)

35.0

In [88]:
'''
NumPy Save & Load
'''

'\nNumPy Save & Load\n'

In [91]:
#Save

n17 = np.array([10,20,30,40,50,60,70,80,90])
np.save('my_numpy',n17)

In [93]:
#Load

n18 = np.load('my_numpy.npy')
n18

array([10, 20, 30, 40, 50, 60, 70, 80, 90])